-- ============================================================================
-- RD Agent Assistant - Fresh DDL + RLS (accounts + emi_collections)
-- ============================================================================
-- Use this file for a clean database setup.
-- It creates tables, constraints, indexes, grants, and RLS policies.

-- ============================================================================
-- 1) TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  village TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '0' CHECK (phone = '0' OR phone ~ '^[0-9]{10}$'),
  emi_amount NUMERIC(12,2) NOT NULL CHECK (emi_amount > 0),
  account_opening_date DATE NOT NULL,
  emi_cycle INTEGER NOT NULL CHECK (emi_cycle IN (15, 30)),
  month_paid_upto INTEGER NOT NULL DEFAULT 0 CHECK (month_paid_upto >= 0),
  next_emi_date DATE NOT NULL,
  active_status BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.emi_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  emis_paid INTEGER NOT NULL DEFAULT 1 CHECK (emis_paid >= 1),
  payment_date DATE NOT NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL CHECK (year >= 2000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ux_emi_one_collection_per_account_per_day UNIQUE (account_id, payment_date)
);

-- ============================================================================
-- 2) INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_accounts_active_status
ON public.accounts(active_status);

CREATE INDEX IF NOT EXISTS idx_accounts_village
ON public.accounts(village);

CREATE INDEX IF NOT EXISTS idx_emi_collections_payment_date
ON public.emi_collections(payment_date);

CREATE INDEX IF NOT EXISTS idx_emi_collections_account_id
ON public.emi_collections(account_id);

CREATE INDEX IF NOT EXISTS idx_emi_collections_year_month
ON public.emi_collections(year, month);

-- ============================================================================
-- 3) GRANTS (required before RLS can allow access)
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.accounts TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.emi_collections TO anon, authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.accounts_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.emi_collections_id_seq TO anon, authenticated;

-- ============================================================================
-- 4) ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emi_collections ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5) RLS POLICIES - ACCOUNTS
-- ============================================================================

DROP POLICY IF EXISTS accounts_select_policy ON public.accounts;
DROP POLICY IF EXISTS accounts_insert_policy ON public.accounts;
DROP POLICY IF EXISTS accounts_update_policy ON public.accounts;
DROP POLICY IF EXISTS accounts_delete_policy ON public.accounts;

-- For this app, client requests use anon key unless user auth is added.
-- Allow both anon and authenticated roles.
CREATE POLICY accounts_select_policy
ON public.accounts FOR SELECT
USING (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY accounts_insert_policy
ON public.accounts FOR INSERT
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY accounts_update_policy
ON public.accounts FOR UPDATE
USING (auth.role() IN ('anon', 'authenticated'))
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY accounts_delete_policy
ON public.accounts FOR DELETE
USING (auth.role() IN ('anon', 'authenticated'));

-- ============================================================================
-- 6) RLS POLICIES - EMI_COLLECTIONS
-- ============================================================================

DROP POLICY IF EXISTS emi_collections_select_policy ON public.emi_collections;
DROP POLICY IF EXISTS emi_collections_insert_policy ON public.emi_collections;
DROP POLICY IF EXISTS emi_collections_update_policy ON public.emi_collections;
DROP POLICY IF EXISTS emi_collections_delete_policy ON public.emi_collections;

CREATE POLICY emi_collections_select_policy
ON public.emi_collections FOR SELECT
USING (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY emi_collections_insert_policy
ON public.emi_collections FOR INSERT
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY emi_collections_update_policy
ON public.emi_collections FOR UPDATE
USING (auth.role() IN ('anon', 'authenticated'))
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY emi_collections_delete_policy
ON public.emi_collections FOR DELETE
USING (auth.role() IN ('anon', 'authenticated'));

-- ============================================================================
-- END
-- ============================================================================

-- ============================================================================
-- NOTES FOR DATA VALIDATION (handled in app):
-- ============================================================================
-- 1. Phone: must be 0 or 10-digit number (validated in app)
-- 2. Village: defaults to empty string if not provided
-- 3. EMI Cycle: auto-calculated from account_opening_date
-- 4. Next EMI Date: calculated in app based on cycle
-- 5. Month Paid Upto: tracks highest month paid (1-12 or year-month)
-- 6. Account Number: unique identifier, must be provided
-- 7. emis_paid: number of EMIs paid in one collection record (default 1)
--    amount = emi_amount * emis_paid (total for the record)
-- 8. active_status: boolean flag indicating if account is active/present in current extraction
--    - TRUE: Account was found in the most recent web extraction (active)
--    - FALSE: Account was NOT found in the most recent web extraction (inactive)
--    - Auto-updated during extraction process; default is FALSE for new accounts
--
-- Format examples:
--   account_opening_date: YYYY-MM-DD (stored), displayed as "dd-MMM-YYYY"
--   next_emi_date: YYYY-MM-DD (stored), displayed as "dd-mmm-yyyy"
--   active_status: FALSE (default for new accounts), updated to TRUE/FALSE during extraction
