-- ============================================================================
-- RD Agent Assistant - Incremental Migration
-- Adds: accounts.remarks, accounts.cif_number, emi_collections.payment_mode,
--       villages table + FK link from accounts.village
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1) ACCOUNTS TABLE CHANGES
-- ============================================================================

ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS remarks TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cif_number TEXT NOT NULL DEFAULT '';

-- Keep village compatible with FK target (non-null empty string default)
UPDATE public.accounts
SET village = ''
WHERE village IS NULL;

ALTER TABLE public.accounts
  ALTER COLUMN village SET DEFAULT '',
  ALTER COLUMN village SET NOT NULL;



-- ============================================================================
-- 2) EMI_COLLECTIONS TABLE CHANGES
-- ============================================================================

ALTER TABLE public.emi_collections
  ADD COLUMN IF NOT EXISTS payment_mode TEXT NOT NULL DEFAULT 'CASH';

-- Normalize any legacy values if column already existed
UPDATE public.emi_collections
SET payment_mode = UPPER(COALESCE(payment_mode, 'CASH'));

-- Enforce allowed values: CASH or ONLINE
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_emi_collections_payment_mode'
      AND conrelid = 'public.emi_collections'::regclass
  ) THEN
    ALTER TABLE public.emi_collections
      ADD CONSTRAINT chk_emi_collections_payment_mode
      CHECK (payment_mode IN ('CASH', 'ONLINE'));
  END IF;
END $$;

-- ============================================================================
-- 3) CREATE VILLAGES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.villages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  village_name TEXT NOT NULL DEFAULT '' UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure blank/default village row exists (needed because accounts.village default is '')
INSERT INTO public.villages (village_name)
VALUES ('')
ON CONFLICT (village_name) DO NOTHING;

-- Backfill villages from existing accounts data
INSERT INTO public.villages (village_name)
SELECT DISTINCT COALESCE(village, '')
FROM public.accounts
ON CONFLICT (village_name) DO NOTHING;

-- ============================================================================
-- 4) LINK ACCOUNTS.VILLAGE -> VILLAGES.VILLAGE_NAME (FK)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_accounts_village_name'
      AND conrelid = 'public.accounts'::regclass
  ) THEN
    ALTER TABLE public.accounts
      ADD CONSTRAINT fk_accounts_village_name
      FOREIGN KEY (village)
      REFERENCES public.villages(village_name)
      ON UPDATE CASCADE
      ON DELETE RESTRICT;
  END IF;
END $$;

-- Existing index on accounts(village) is already present in your MIGRATIONS.sql.
-- No extra index is required on villages.village_name because UNIQUE creates one.

-- ============================================================================
-- 5) RLS + POLICIES FOR VILLAGES
-- ============================================================================

ALTER TABLE public.villages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS villages_select_authenticated ON public.villages;
DROP POLICY IF EXISTS villages_insert_authenticated ON public.villages;
DROP POLICY IF EXISTS villages_update_authenticated ON public.villages;
DROP POLICY IF EXISTS villages_delete_authenticated ON public.villages;
DROP POLICY IF EXISTS villages_select_access ON public.villages;
DROP POLICY IF EXISTS villages_insert_access ON public.villages;
DROP POLICY IF EXISTS villages_update_access ON public.villages;
DROP POLICY IF EXISTS villages_delete_access ON public.villages;

CREATE POLICY villages_select_access
ON public.villages FOR SELECT
USING (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY villages_insert_access
ON public.villages FOR INSERT
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY villages_update_access
ON public.villages FOR UPDATE
USING (auth.role() IN ('anon', 'authenticated'))
WITH CHECK (auth.role() IN ('anon', 'authenticated'));

CREATE POLICY villages_delete_access
ON public.villages FOR DELETE
USING (auth.role() IN ('anon', 'authenticated'));

-- Grants for app API usage (anon + authenticated)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.villages TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.villages_id_seq TO anon, authenticated;

COMMIT;
